# 使用 Alpine Linux 3.20.1 作为基础镜像
FROM alpine:3.20.1

# 设置 SQLynx 的版本号,构建时使用 --build-arg SQLYNX_VERSION=<指定版本号> 来指定版本
ARG SQLYNX_VERSION=3.5.0

# 设置工作目录为 /apps
WORKDIR /apps

# 替换默认的 Alpine 镜像源为中国科技大学的镜像源
# RUN set -eux && sed -i 's/dl-cdn.alpinelinux.org/mirrors.ustc.edu.cn/g' /etc/apk/repositories

# 更新并安装必要的软件包,包括 bash、OpenJDK 8 JRE、wget、curl 等
# 下载并解压 SQLynx 应用程序,重命名为 /apps/sqlynx(自动获取第一个匹配的文件夹)
# 创建启动脚本 start.sh,包含启动 SQLynx、处理信号和输出日志
RUN set -x \
  && apk update -v \
  && apk add --no-cache bash openjdk8-jre openjdk8-jre-lib wget curl iputils unzip zip \
  && apk cache clean \
  && rm -rf /var/cache/apk/* \
  && wget -O sqlynx.zip http://maicong-software-1302946156.cos.ap-beijing.myqcloud.com/software/sqlynx_linux_no_jdk_${SQLYNX_VERSION}.zip \
  && unzip sqlynx.zip \
  && mv $(find . -type d -name '*sqlynx*' | head -n 1) /apps/sqlynx \
  && rm -rf sqlynx.zip \
  && touch /apps/sqlynx/log/maicong-sqlynx-console.log \
  && echo -e '#!/bin/bash\n bash /apps/sqlynx/sqlynx-ide.sh start \n trap "echo Stopping SQLynx...;bash /apps/sqlynx/sqlynx-ide.sh stop; exit 0" SIGINT SIGTERM \n tail -f /apps/sqlynx/log/maicong-sqlynx-console.log & \n wait $!' > /apps/sqlynx/start.sh && chmod a+x /apps/sqlynx/start.sh

# 暴露端口 18888
EXPOSE 18888
# 设置容器卷,用于持久化存储数据,data 数据,log 日志
VOLUME /apps/sqlynx/data /apps/sqlynx/log

# 定义容器启动时运行的命令
CMD ["/bin/bash", "/apps/sqlynx/start.sh"]
